### PR TITLE
Adding support for snippet update

### PR DESCRIPTION
**Pull request by momirjalili**
Hi Currently only dynamic snippets support, this is an effort to add update capability for normal snippets and cover https://docs.fastly.com/api/config#snippet_e74c500822f252e309a03e0d2727d7b3

I added unittests, but since all the tests were run with a particular service id, I didn't know the policy of how new contributions are accepted. I would be happy if you guide me on this.

### CODE REVIEW

**Comment by sethvargo** [comment]
Tests look sad on Travis. Did you commit the interactions?

**Comment by momirjalili** [comment]
@sethvargo should I run them with my random test service?

**Comment by sethvargo** [comment]
@momirjalili yea, and then manually edit the YAML to remove your API key and replace it with `XXX...` - see the other ones for examples

**Comment by momirjalili** [comment]
@sethvargo sorry, it took me a while to get back to this, now the tests are passing.

**Pull request merged**
